import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createSourceClient,parsePlatforms,parseCard,parseDetail,parsePage,prepareManifest,englishSubtitleLanguage,parseEnglishVTT,parseEpisode,parseSlug,SourceError} from '../services/source.ts';
const captured=JSON.parse(fs.readFileSync(new URL('./fixtures/public-contracts.json',import.meta.url)));
const fixture=label=>structuredClone(captured.requests.find(r=>r.label===label).data);
const detail=fixture('detail:eternal-illumination'),card=Object.fromEntries(['id','slug','title','cover','platform','total_episodes','available_episodes','is_new','is_popular'].map(k=>[k,detail[k]]));
const receipt={requestId:'fixture',requestProfile:'observed-desktop-UA',requests:[],freshGuestSessionReceived:true,cached:false};
const manifest='#EXTM3U\n#EXT-X-TARGETDURATION:10\n#EXTINF:10.0,\nhttps://cdn2.dramaflix.net/fixture/one.ts?sign=synthetic-fixture-only\n#EXT-X-ENDLIST\n';
function response(value,status=200,headers={}){return new Response(typeof value==='string'?value:JSON.stringify(value),{status,headers:{'content-type':typeof value==='string'?'application/vnd.apple.mpegurl':'application/json',...headers}});}
function fake(handler){const seen=[];const fn=async(url,options)=>{const u=new URL(url);seen.push({u,options});return handler(u,options,seen.length);};return {fetchImpl:fn,seen};}
function normal(u){if(u.pathname==='/api/config')return response({lang:'en'},200,{'set-cookie':'dd_bilet=synthetic-guest-fixture; Path=/; Secure; HttpOnly'});if(u.pathname==='/api/platforms')return response(fixture('all-platforms'));if(u.pathname==='/api/series/'+detail.slug)return response(detail);if(u.pathname==='/api/series')return response({data:[card],total:1,page:1,limit:40,pages:1});if(u.pathname==='/api/search')return response({data:[card],total:1,page:1,limit:36,pages:1});if(u.pathname==='/api/home')return response(fixture('legacy-home'));if(u.pathname.startsWith('/hls/'))return response(manifest);if(u.pathname.startsWith('/api/subtitles/'))return response([]);throw Error('Unexpected synthetic route');}

test('fresh captured directory preserves all43 including three empty platforms and missing logos',()=>{const p=parsePlatforms(fixture('all-platforms'));assert.equal(p.length,43);assert.equal(p.filter(x=>x.count===0).length,3);assert.equal(p.filter(x=>x.logo===null).length,3);assert(p.every(x=>x.logo===null||x.logo.startsWith('https://dramadunyam.com/logos/')));assert(Object.isFrozen(p));});
test('duplicate or unsafe platform metadata rejects',()=>{assert.throws(()=>parsePlatforms([{name:'../evil',count:1}]));assert.throws(()=>parsePlatforms([{name:'A',count:1},{name:'A',count:1}]));});
test('captured pages/home/search parse with source counts and pagination',()=>{for(const name of ['home-catalogue-page-1','catalogue-page-2','search']){const p=parsePage(fixture(name),receipt);assert(p.items.length>0);assert(p.pages>1);}const c=parseCard(card);assert.equal(c.cover,'https://dramadunyam.com/covers/154805.webp');assert.equal(c.audioEvidence,'sampled-english');});
test('actual search inconsistent counts remain visible warned metadata, not playable guessed bounds',()=>{const p=parsePage(fixture('search'),receipt),bad=p.items.find(c=>c.id==='76946');assert(bad);assert.equal(bad.totalEpisodes,28);assert.equal(bad.availableEpisodes,70);assert(bad.countWarning);assert.throws(()=>parseDetail({...detail,id:bad.id,slug:bad.slug,total_episodes:28,available_episodes:70}));});
test('language metadata never makes unknown English audio claim or blocks original audio',()=>{const c=parseCard({...card,id:'222',slug:'fixture-title',platform:'GoodShort'});assert.equal(c.audioEvidence,'unknown');const cn=parseCard({...card,id:'152742',slug:'fixture-cn',platform:'NetShort'});assert.equal(cn.audioEvidence,'sampled-non-english');assert.equal(cn.catalogueLanguage,'en');const dub=parseCard({...card,id:'333',slug:'dubbed-fixture',title:'[Dubbed] Fixture'});assert.equal(dub.audioEvidence,'dubbed-label-unverified');});
test('detail count-derived55 ordinals retain qualification, only covered counts available',()=>{const d=parseDetail(detail);assert.equal(d.episodes.length,55);assert(d.episodes[54].advertisedAvailable);assert.equal(d.episodes[19].number,20);const partial=parseDetail({...detail,available_episodes:3,episodes_in_db:2});assert(partial.episodes[1].advertisedAvailable);assert.equal(partial.episodes[2].advertisedAvailable,false);});
test('detail EN identity mismatch and corrupt counts reject',()=>{assert.throws(()=>parseDetail({...detail,language:'ar'}));assert.throws(()=>parseDetail(detail,{id:'999',slug:detail.slug,platform:detail.platform}));assert.throws(()=>parseDetail({...detail,episodes_in_db:9999}));assert.throws(()=>parseDetail({...detail,total_episodes:-1}));});
test('unsafe poster is discarded rather than requested',()=>{assert.equal(parseCard({...card,cover:'https://foreign.invalid/covers/a.webp'}).cover,null);assert.equal(parseCard({...card,cover:'javascript:alert(1)'}).cover,null);assert.equal(parseCard({...card,cover:'/covers/a.webp?token=fixture'}).cover,null);});
test('empty catalogue is explicit with no invented title',()=>{const p=parsePage({data:[],total:0,page:1,pages:0,limit:40},receipt);assert.equal(p.items.length,0);assert.equal(p.total,0);});
test('invalid page schema, duplicate rows, wrong platform reject',()=>{assert.throws(()=>parsePage({data:[card,card],total:2,page:1,pages:1,limit:40},receipt));assert.throws(()=>parsePage({data:[card],total:1,page:1,pages:1,limit:40},receipt,false,'Nope'));assert.throws(()=>parsePage({data:[],total:1,page:0,pages:1,limit:40},receipt));});
test('strict episode and slug boundaries reject arrays/path injection',()=>{for(const v of [0,-1,1.1,5001,[],null,'01','1e2'])assert.throws(()=>parseEpisode(v));assert.equal(parseEpisode('20'),20);assert.equal(parseEpisode(55),55);for(const x of ['../evil','https://site.test','a/b','a?b'])assert.throws(()=>parseSlug(x));});
test('HLS relative references preserve exact signed query on published origin',()=>{const m=prepareManifest(manifest,'/hls/154805/20/playlist.m3u8');assert(m.body.includes('?sign=synthetic-fixture-only'));assert.equal(m.referenceCount,1);assert.deepEqual(m.referenceHosts,['cdn2.dramaflix.net']);const r=prepareManifest(manifest.replace('https://cdn2.dramaflix.net/fixture/one.ts','/fixture/one.ts'),'/hls/154805/20/playlist.m3u8');assert(r.body.includes('https://dramadunyam.com/fixture/one.ts?sign=synthetic-fixture-only'));});
test('foreign HTTP/credential/master/encryption HLS references reject with no media fetch',()=>{for(const changed of [manifest.replace('cdn2.dramaflix.net','evil.invalid'),manifest.replace('https:','http:'),manifest.replace('https://cdn2','https://user:pass@cdn2'),manifest.replace('#EXTINF','#EXT-X-KEY:METHOD=AES-128,URI="key"\n#EXTINF'),manifest.replace('#EXTINF','#EXT-X-STREAM-INF:BANDWIDTH=1\n#EXTINF')])assert.throws(()=>prepareManifest(changed,'/hls/154805/20/playlist.m3u8'));});
test('only English advertised subtitle language selected; no Arabic fallback',()=>{assert.equal(englishSubtitleLanguage(['AR','ZH']),null);assert.equal(englishSubtitleLanguage(['AR','en-US']),'en-US');assert.equal(englishSubtitleLanguage(['English']),'English');assert.throws(()=>englishSubtitleLanguage(['en/../secret']));});
test('English VTT cues are bounded and markup stripped',()=>{assert.deepEqual(parseEnglishVTT('WEBVTT\n\n1\n00:00:01.000 --> 00:00:03.000\n<b>Hello</b> &amp; welcome.\n'),[{start:1,end:3,text:'Hello & welcome.'}]);assert.throws(()=>parseEnglishVTT('WEBVTT\n\n00:00:04.000 --> 00:00:03.000\nbad'));});
test('real-path metadata client issues fresh guest cookie only sameorigin; receipts redacted',async()=>{const f=fake(normal),c=createSourceClient(f);const p=await c.fetchPlatformDirectory(new AbortController().signal);assert.equal(p.platforms.length,43);assert.equal(p.receipt.requests.length,2);assert.equal(p.cached,false);assert.equal(f.seen[0].options.headers.Cookie,undefined);assert.equal(f.seen[1].options.headers.Cookie,'dd_bilet=synthetic-guest-fixture');assert(!JSON.stringify(p.receipt).includes('synthetic-guest-fixture'));assert(!JSON.stringify(p.receipt).includes('lang='));});
test('memory cache is bounded no fresh claims on cache hits; clear refreshes',async()=>{const f=fake(normal),c=createSourceClient(f),s=new AbortController().signal;await c.fetchPlatformDirectory(s);const cached=await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,2);assert.equal(cached.cached,true);assert.equal(cached.receipt.cached,true);c.clearCache();await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,4);});
test('clear cache epoch prevents older in-flight metadata repopulating new generation',async()=>{let release;const gate=new Promise(r=>release=r);const f=fake(async u=>{if(u.pathname==='/api/platforms'&&!release.done){await gate;release.done=true;}return normal(u);}),c=createSourceClient(f),s=new AbortController().signal;const pending=c.fetchPlatformDirectory(s);while(f.seen.length<2)await new Promise(r=>setTimeout(r,1));c.clearCache();release();await pending;await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,4);});
test('general resolver supports issued detail E1/E55, not fixed4 late samples',async()=>{const generic={...detail,id:'987654',slug:'new-real-catalogue-title',platform:'SerialPlus',title:'Original audio title'};const f=fake(u=>u.pathname==='/api/series/'+generic.slug?response(generic):normal(u)),c=createSourceClient(f),s=new AbortController().signal;const d=await c.fetchDetail(generic.slug,s);const r=await c.resolveEpisode(d,55,s);assert.equal(r.identity.seriesId,'987654');assert.equal(r.episodeNumber,55);assert.equal(r.subtitleStatus,'no-english-sidecar');assert.equal(r.transport,'app-cache-manifest-direct-https-segments');assert.equal(r.cdnCredentialsAttached,false);assert.equal(f.seen.filter(x=>x.u.hostname!=='dramadunyam.com').length,0);assert(f.seen.some(x=>x.u.pathname==='/hls/987654/55/playlist.m3u8'));});
test('forged detail and nonadvertised ordinal reject before any request',async()=>{const f=fake(normal),c=createSourceClient(f),s=new AbortController().signal;await assert.rejects(c.resolveEpisode(parseDetail(detail),20,s),e=>e.code==='DETAIL_NOT_ISSUED');assert.equal(f.seen.length,0);const d=await c.fetchDetail(detail.slug,s),before=f.seen.length;await assert.rejects(c.resolveEpisode(d,56,s),e=>e.code==='EPISODE_NOT_ADVERTISED');assert.equal(f.seen.length,before);});
test('English sidecar fetch is ordinary sameorigin only; no other-language file',async()=>{const f=fake(u=>u.pathname.startsWith('/api/subtitles/')?response(['AR','EN']):u.pathname.startsWith('/sub/')?response('WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nEnglish fixture.'):normal(u)),c=createSourceClient(f),s=new AbortController().signal;const d=await c.fetchDetail(detail.slug,s),r=await c.resolveEpisode(d,20,s);assert.equal(r.subtitleStatus,'english-sidecar');assert.equal(r.englishSubtitleCues.length,1);assert(f.seen.some(x=>x.u.pathname==='/sub/154805/20/EN'));assert(!f.seen.some(x=>x.u.pathname.endsWith('/AR')));});
test('gated HTTP403 remains explicit error, never auto-unlocks/retryloops',async()=>{const f=fake(u=>u.pathname.startsWith('/hls/')?response('guest gate',403):normal(u)),c=createSourceClient(f),s=new AbortController().signal,d=await c.fetchDetail(detail.slug,s);await assert.rejects(c.resolveEpisode(d,20,s),e=>e instanceof SourceError&&e.code==='HTTP_403'&&e.receipt.requests.at(-1).status===403);assert.equal(f.seen.filter(x=>x.u.pathname.startsWith('/hls/')).length,1);});
test('wrong contenttype/json, missing guestcookie and body bound remain typed errors',async()=>{for(const [value,headers,code] of [[{lang:'en'},{},'FRESH_GUEST_SESSION_MISSING'],['notjson',{'content-type':'application/json','set-cookie':'dd_bilet=fixture; Secure'},'INVALID_JSON'],['x'.repeat(131073),{'content-type':'application/json','set-cookie':'dd_bilet=fixture; Secure'},'BODY_LIMIT']]){const f=fake(()=>response(value,200,headers)),c=createSourceClient(f);await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code===code);}});
test('abort before and during stalled fetch produces ABORTED, no stale cache result',async()=>{const a=new AbortController();a.abort();const f=fake(normal),c=createSourceClient(f);await assert.rejects(c.fetchHome(a.signal),e=>e.code==='ABORTED');assert.equal(f.seen.length,0);const b=new AbortController(),c2=createSourceClient({fetchImpl:()=>new Promise(()=>{})});const p=c2.fetchPlatforms(b.signal);setTimeout(()=>b.abort(),10);await assert.rejects(p,e=>e.code==='ABORTED');});
test('whole-operation deadline includes queue and blocked body read',async()=>{const c=createSourceClient({fetchImpl:()=>new Promise(()=>{}),deadlineMs:20});await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code==='DEADLINE_EXCEEDED');});
test('global operation concurrency stays≤2 with normal guest requests',async()=>{let active=0,max=0;const f=fake(async u=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,3));active--;return normal(u);}),c=createSourceClient(f),s=new AbortController().signal;await Promise.all([c.fetchPlatforms(s),c.fetchHome(s),c.searchCatalogue('eternal',{},s),c.fetchCatalogue({},s)]);assert(max<=2);});
test('malicious redirect is rejected, never fetches foreign target',async()=>{const f=fake(()=>{const r=response({lang:'en'});Object.defineProperty(r,'url',{value:'https://foreign.invalid/api/config'});return r;}),c=createSourceClient(f);await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code==='REDIRECT_REJECTED');assert.equal(f.seen.length,1);});

test('current CDN cover and logo paths survive catalogue and saved-card validation',()=>{
 const cover='https://dramaflix.net/dfl-media/img/covers/0123456789abcdef/480.webp';
 assert.equal(parseCard({...card,cover}).cover,cover);
 assert.equal(parsePlatforms([{name:'ShortMax',count:1,logo:'https://dramaflix.net/dfl-media/logos/shortmax.webp'}])[0].logo,'https://dramaflix.net/dfl-media/logos/shortmax.webp');
 for(const url of [cover+'?token=fixture',cover.replace('dramaflix.net','evil.invalid'),cover.replace('/480.webp','/../../secret.webp'),'https://dramaflix.net/other/a.webp'])assert.equal(parseCard({...card,cover:url}).cover,null);
});

for(const [name,target,segment] of [
 ['same-origin','https://dramadunyam.com/vr/dr/hls/fixture_720/main.m3u8?auth_key=synthetic','https://dramadunyam.com/vr/dr/hls/fixture_720/main/segment-1.ts'],
 ['external','https://v-mps.crazymaplestudios.com/vod-112094/fixture/ld.m3u8','https://v-mps.crazymaplestudios.com/vod-112094/fixture/main/segment-1.ts'],
])test(`${name} HLS redirect resolves relative segments against the final URL`,async()=>{
 const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response('#EXTM3U\n#EXTINF:10,\nmain/segment-1.ts\n#EXT-X-ENDLIST\n'):normal(u));
 const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,20,signal);
 assert.equal(r.type,'hls');assert(r.manifestBody.includes(segment));
 const request=f.seen.find(x=>x.u.href===target);assert.equal(request.options.redirect,'manual');
 assert.equal(request.options.headers.Cookie,name==='same-origin'?'dd_bilet=synthetic-guest-fixture':undefined);
 assert(!JSON.stringify(r.receipt).includes('auth_key'));assert(!JSON.stringify(r.receipt).includes('synthetic-guest-fixture'));
});

test('redirected master chooses a bounded Full HD variant and resolves its media playlist',async()=>{
 const target='https://dramadunyam.com/vr/fr/vt/fixture/master.m3u8';
 const master='#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=100000,RESOLUTION=360x640\nlow.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=608x1080\nhigh.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=900000,RESOLUTION=2160x3840\nuhd.m3u8\n';
 const f=fake(u=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response(master):u.pathname.endsWith('/high.m3u8')?response('#EXTM3U\n#EXTINF:10,\nmain/segment-1.ts\n#EXT-X-ENDLIST\n'):normal(u));
 const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,20,signal);
 assert.equal(r.type,'hls');assert(r.manifestBody.includes('https://dramadunyam.com/vr/fr/vt/fixture/main/segment-1.ts'));
 assert(!f.seen.some(x=>x.u.pathname.endsWith('/uhd.m3u8')));
});

for(const target of ['https://ns-aws-cdn.netshort.com/fixture?mime_type=video_mp4&auth_key=synthetic','https://hwztakavideoto.dramaboxdb.com/fixture/episode.720p.mp4','https://v45e-eu.tiktokcdn.com/fixture?mime_type=video_mp4&auth_key=synthetic'])test('direct MP4 uses HEAD validation without downloading video in JavaScript: '+new URL(target).hostname,async()=>{
 const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response('',200,{'content-type':'video/mp4'}):normal(u));
 const c=createSourceClient({...f,now:()=>100000}),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,20,signal);
 assert.equal(r.type,'mp4');assert.equal(r.uri,target);assert.equal(r.manifestBody,null);assert.equal(r.manifestSHA256,null);assert.equal(r.expiresAt,400000);
 const requests=f.seen.filter(x=>x.u.href===target);assert.equal(requests.length,1);assert.equal(requests[0].options.method,'HEAD');assert.equal(requests[0].options.headers.Cookie,undefined);
 assert.equal(r.receipt.requests.find(x=>x.host===new URL(target).hostname).bytesRead,0);
 assert(!JSON.stringify(r.receipt).includes('auth_key'));
});

test('media redirects reject foreign hosts, credentials, downgrade and loops before forwarding',async()=>{
 for(const target of ['https://evil.invalid/video.m3u8','http://dramadunyam.com/video.m3u8','https://user:pass@dramadunyam.com/video.m3u8','https://dramadunyam.com/hls/154805/20/playlist.m3u8']){
  const f=fake(u=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):normal(u)),c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);
  await assert.rejects(c.resolveEpisode(d,20,signal),e=>e.code==='REDIRECT_REJECTED');assert.equal(f.seen.filter(x=>x.u.pathname.startsWith('/hls/')).length,1);
 }
});

test('portrait master preserves separate audio and validates public fMP4 children without guest cookies',async()=>{
 const base='https://dramadunyam.com/vr/fr/vt/fixture/';
 const master='#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,URI="audio.m3u8",GROUP-ID="audio",NAME="en-US",DEFAULT=NO,AUTOSELECT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=1080x1920,AUDIO="audio"\nvideo.m3u8\n';
 const child='#EXTM3U\n#EXT-X-MAP:URI="init.mp4"\n#EXTINF:10,\nfragment.mp4\n#EXT-X-ENDLIST\n';
 const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:base+'master.m3u8'}):u.href===base+'master.m3u8'?response(master):u.href===base+'video.m3u8'||u.href===base+'audio.m3u8'?response(child):normal(u));
 const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,20,signal);
 assert.equal(r.type,'hls');assert.equal(r.transport,'app-cache-master-direct-https-playlists-and-segments');assert(r.manifestBody.includes('AUDIO="audio"'));assert(r.manifestBody.includes('URI="'+base+'audio.m3u8"'));assert(r.manifestBody.includes(base+'video.m3u8'));
 for(const request of f.seen.filter(x=>/\/(?:audio|video)\.m3u8$/.test(x.u.pathname)))assert.equal(request.options.headers.Cookie,undefined);
});

test('a master with only oversized or unknown dimensions fails without fetching a child',async()=>{
 const master='#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=2160x3840\nlarge.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=100000\nunknown.m3u8\n';
 const f=fake(u=>u.pathname.startsWith('/hls/')?response(master):normal(u)),c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);
 await assert.rejects(c.resolveEpisode(d,20,signal),e=>['UNSUPPORTED_MANIFEST','INVALID_MANIFEST'].includes(e.code));assert(!f.seen.some(x=>/\/(?:large|unknown)\.m3u8$/.test(x.u.pathname)));
});

 test('PineDrama exact MP4 host does not permit sibling hosts, userinfo, ports, downgrade, fragments or missing mime',async()=>{for(const target of ['https://v45f-eu.tiktokcdn.com/fixture?mime_type=video_mp4','https://v45e-eu.tiktokcdn.com.evil.invalid/fixture?mime_type=video_mp4','http://v45e-eu.tiktokcdn.com/fixture?mime_type=video_mp4','https://user:pass@v45e-eu.tiktokcdn.com/fixture?mime_type=video_mp4','https://v45e-eu.tiktokcdn.com:8443/fixture?mime_type=video_mp4','https://v45e-eu.tiktokcdn.com/fixture?mime_type=video_mp4#fragment','https://v45e-eu.tiktokcdn.com/fixture?mime_type=audio_mp4','https://v45e-eu.tiktokcdn.com/fixture']){const f=fake(u=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):normal(u)),c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,1,signal),e=>e.code==='REDIRECT_REJECTED');assert.equal(f.seen.filter(x=>x.u.hostname!=='dramadunyam.com').length,0);}});
 test('PineDrama MP4 HEAD rejects non-video content without downloading a body',async()=>{const target='https://v45e-eu.tiktokcdn.com/fixture?mime_type=video_mp4';const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response('',200,{'content-type':'text/html'}):normal(u)),c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,1,signal),e=>e.code==='INVALID_CONTENT_TYPE');assert.equal(f.seen.find(x=>x.u.href===target).options.method,'HEAD');assert.equal(f.seen.find(x=>x.u.href===target).options.headers.Cookie,undefined);});
for(const host of ['v77e.tiktokcdn.com','v19e.tiktokcdn.com','v16me.tiktokcdn.com'])test(`observed PineDrama ${host} MP4 redirect uses cookie-free HEAD`,async()=>{const target=`https://${host}/fixture?mime_type=video_mp4`;const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response('',200,{'content-type':'video/mp4'}):normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,21,signal);assert.equal(r.type,'mp4');assert.equal(r.uri,target);const req=f.seen.find(x=>x.u.href===target);assert.equal(req.options.method,'HEAD');assert.equal(req.options.headers.Cookie,undefined);assert.equal(r.receipt.requests.find(x=>x.host===host).bytesRead,0);});
for(const host of ['v77e.tiktokcdn.com','v19e.tiktokcdn.com','v16me.tiktokcdn.com'])test(`PineDrama ${host} retains exact host and MIME validation`,async()=>{for(const target of [`https://${host}.evil.invalid/fixture?mime_type=video_mp4`,`https://v77f.tiktokcdn.com/fixture?mime_type=video_mp4`,`http://${host}/fixture?mime_type=video_mp4`,`https://user:pass@${host}/fixture?mime_type=video_mp4`,`https://${host}:444/fixture?mime_type=video_mp4`,`https://${host}/fixture?mime_type=video_mp4#x`,`https://${host}/fixture`,`https://${host}/fixture?mime_type=audio_mp4`]){const f=fake(u=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,21,signal),e=>e.code==='REDIRECT_REJECTED');assert(!f.seen.some(x=>x.u.hostname!== 'dramadunyam.com'));}});
test('verified PineDrama HEAD503 uses exact two-byte ranged preflight',async()=>{const target='https://v16me.tiktokcdn.com/fixture?mime_type=video_mp4';const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?o.method==='HEAD'?response('',503,{'content-type':'video/mp4'}):response('ab',206,{'content-type':'video/mp4','content-range':'bytes 0-1/5068049','content-length':'2'}):normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal),r=await c.resolveEpisode(d,50,signal);assert.equal(r.type,'mp4');const req=f.seen.filter(x=>x.u.href===target);assert.deepEqual(req.map(x=>x.options.method),['HEAD','GET']);assert.equal(req[1].options.headers.Range,'bytes=0-1');assert.equal(req[1].options.credentials,'omit');assert.equal(req[1].options.redirect,'manual');for(const x of req)assert.equal(x.options.headers.Cookie,undefined);assert.equal(r.receipt.requests.filter(x=>x.host==='v16me.tiktokcdn.com').at(-1).bytesRead,2);});
test('PineDrama ranged preflight rejects ignored ranges, malformed media, identities and lengths',async()=>{const target='https://v16me.tiktokcdn.com/fixture?mime_type=video_mp4';for(const [status,type,range,body,length,finalURL] of [[200,'video/mp4','bytes 0-1/10','ab','2'],[206,'text/html','bytes 0-1/10','ab','2'],[206,'video/mp4','bytes 1-2/10','ab','2'],[206,'video/mp4','bytes 0-1/1','ab','2'],[206,'video/mp4','bytes 0-1/10','a','2'],[206,'video/mp4','bytes 0-1/10','abc','3'],[206,'video/mp4','bytes 0-1/10','ab','2','https://evil.invalid/fixture'],[302,'video/mp4',null,'ab','2']]){const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?o.method==='HEAD'?response('',503):Object.defineProperty(response(body,status,{'content-type':type,'content-range':range??'','content-length':length,location:'https://evil.invalid/fixture'}),'url',{value:finalURL??target}):normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,50,signal));assert(!f.seen.some(x=>x.u.hostname==='evil.invalid'));}});
test('PineDrama range body overflow cancels actual fetch signal and never uses arrayBuffer',async()=>{const target='https://v16me.tiktokcdn.com/fixture?mime_type=video_mp4';let cancelled=false,buffered=false;const f=fake((u,o)=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?o.method==='HEAD'?response('',503):{url:target,status:206,headers:new Headers({'content-type':'video/mp4','content-range':'bytes 0-1/10','content-length':'2'}),body:new ReadableStream({pull(c){c.enqueue(new Uint8Array([1,2,3]));},cancel(){cancelled=true;}}),arrayBuffer(){buffered=true;throw Error('unbounded')} }:normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,50,signal),e=>e.code==='BODY_LIMIT');await new Promise(r=>setImmediate(r));assert(cancelled);assert(!buffered);assert(f.seen.find(x=>x.u.href===target&&x.options.method==='GET').options.signal.aborted);});
test('non503 HEAD and nonTikTok errors do not trigger ranged fallback',async()=>{for(const [host,status] of [['v16me.tiktokcdn.com',500],['ns-aws-cdn.netshort.com',503]]){const target=`https://${host}/fixture?mime_type=video_mp4`;const f=fake(u=>u.pathname.startsWith('/hls/')?response('',302,{location:target}):u.href===target?response('',status):normal(u));const c=createSourceClient(f),signal=new AbortController().signal,d=await c.fetchDetail(detail.slug,signal);await assert.rejects(c.resolveEpisode(d,50,signal),e=>e.code===`HTTP_${status}`);assert.equal(f.seen.filter(x=>x.u.href===target).length,1);}});
