import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createSourceClient,parsePlatforms,parseCard,parseDetail,parsePage,prepareManifest,englishSubtitleLanguage,parseEnglishVTT,parseEpisode,parseSlug,SourceError} from '../services/source.ts';
const captured=JSON.parse(fs.readFileSync(new URL('./fixtures/public-contracts.json',import.meta.url)));
const fixture=label=>structuredClone(captured.requests.find(r=>r.label===label).data);
const detail=fixture('detail:eternal-illumination'),card=Object.fromEntries(['id','slug','title','cover','platform','total_episodes','available_episodes','is_new','is_popular'].map(k=>[k,detail[k]]));
const receipt={requestId:'fixture',requestProfile:'observed-desktop-UA',requests:[],freshGuestSessionReceived:true,cached:false};
const manifest='#EXTM3U\n#EXT-X-TARGETDURATION:10\n#EXTINF:10.0,\nhttps://cdn2.dramaflix.net/fixture/one.ts?sign=synthetic-fixture-only\n#EXT-X-ENDLIST\n';
function response(value,status=200,headers={}){return new Response(typeof value==='string'?value:JSON.stringify(value),{status,headers:{'content-type':typeof value==='string'?'application/vnd.apple.mpegurl':'application/json',...headers}});}
function fake(handler){const seen=[];const fn=async(url,options)=>{const u=new URL(url);seen.push({u,options});return handler(u,options,seen.length);};return {fetchImpl:fn,seen};}
function normal(u){if(u.pathname==='/api/config')return response({lang:'en'},200,{'set-cookie':'dd_bilet=synthetic-guest-fixture; Path=/; Secure; HttpOnly'});if(u.pathname==='/api/platforms')return response(fixture('all-platforms'));if(u.pathname==='/api/series/'+detail.slug)return response(detail);if(u.pathname==='/api/series')return response({data:[card],total:1,page:1,limit:40,pages:1});if(u.pathname==='/api/search')return response({data:[card],total:1,page:1,limit:36,pages:1});if(u.pathname==='/api/home')return response(fixture('legacy-home'));if(u.pathname.startsWith('/hls/'))return response(manifest);if(u.pathname.startsWith('/api/subtitles/'))return response([]);throw Error('Unexpected synthetic route');}

test('fresh captured directory preserves all43 including three empty platforms and missing logos',()=>{const p=parsePlatforms(fixture('all-platforms'));assert.equal(p.length,43);assert.equal(p.filter(x=>x.count===0).length,3);assert.equal(p.filter(x=>x.logo===null).length,3);assert(p.every(x=>x.logo===null||x.logo.startsWith('https://dramadunyam.com/logos/')));assert(Object.isFrozen(p));});
test('duplicate or unsafe platform metadata rejects',()=>{assert.throws(()=>parsePlatforms([{name:'../evil',count:1}]));assert.throws(()=>parsePlatforms([{name:'A',count:1},{name:'A',count:1}]));});
test('captured pages/home/search parse with source counts and pagination',()=>{for(const name of ['home-catalogue-page-1','catalogue-page-2','search']){const p=parsePage(fixture(name),receipt);assert(p.items.length>0);assert(p.pages>1);}const c=parseCard(card);assert.equal(c.cover,'https://dramadunyam.com/covers/154805.webp');assert.equal(c.audioEvidence,'sampled-english');});
test('actual search inconsistent counts remain visible warned metadata, not playable guessed bounds',()=>{const p=parsePage(fixture('search'),receipt),bad=p.items.find(c=>c.id==='76946');assert(bad);assert.equal(bad.totalEpisodes,28);assert.equal(bad.availableEpisodes,70);assert(bad.countWarning);assert.throws(()=>parseDetail({...detail,id:bad.id,slug:bad.slug,total_episodes:28,available_episodes:70}));});
test('language metadata never makes unknown English audio claim or blocks original audio',()=>{const c=parseCard({...card,id:'222',slug:'fixture-title',platform:'GoodShort'});assert.equal(c.audioEvidence,'unknown');const cn=parseCard({...card,id:'152742',slug:'fixture-cn',platform:'NetShort'});assert.equal(cn.audioEvidence,'sampled-non-english');assert.equal(cn.catalogueLanguage,'en');const dub=parseCard({...card,id:'333',slug:'dubbed-fixture',title:'[Dubbed] Fixture'});assert.equal(dub.audioEvidence,'dubbed-label-unverified');});
test('detail count-derived55 ordinals retain qualification, only covered counts available',()=>{const d=parseDetail(detail);assert.equal(d.episodes.length,55);assert(d.episodes[54].advertisedAvailable);assert.equal(d.episodes[19].number,20);const partial=parseDetail({...detail,available_episodes:3,episodes_in_db:2});assert(partial.episodes[1].advertisedAvailable);assert.equal(partial.episodes[2].advertisedAvailable,false);});
test('detail EN identity mismatch and corrupt counts reject',()=>{assert.throws(()=>parseDetail({...detail,language:'ar'}));assert.throws(()=>parseDetail(detail,{id:'999',slug:detail.slug,platform:detail.platform}));assert.throws(()=>parseDetail({...detail,episodes_in_db:9999}));assert.throws(()=>parseDetail({...detail,total_episodes:-1}));});
test('unsafe poster is discarded rather than requested',()=>{assert.equal(parseCard({...card,cover:'https://foreign.invalid/covers/a.webp'}).cover,null);assert.equal(parseCard({...card,cover:'javascript:alert(1)'}).cover,null);assert.equal(parseCard({...card,cover:'/covers/a.webp?token=fixture'}).cover,null);});
test('empty catalogue is explicit with no invented title',()=>{const p=parsePage({data:[],total:0,page:1,pages:0,limit:40},receipt);assert.equal(p.items.length,0);assert.equal(p.total,0);});
test('invalid page schema, duplicate rows, wrong platform reject',()=>{assert.throws(()=>parsePage({data:[card,card],total:2,page:1,pages:1,limit:40},receipt));assert.throws(()=>parsePage({data:[card],total:1,page:1,pages:1,limit:40},receipt,false,'Nope'));assert.throws(()=>parsePage({data:[],total:1,page:0,pages:1,limit:40},receipt));});
test('strict episode and slug boundaries reject arrays/path injection',()=>{for(const v of [0,-1,1.1,5001,[],null,'01','1e2'])assert.throws(()=>parseEpisode(v));assert.equal(parseEpisode('20'),20);assert.equal(parseEpisode(55),55);for(const x of ['../evil','https://site.test','a/b','a?b'])assert.throws(()=>parseSlug(x));});
test('HLS relative references preserve exact signed query on published origin',()=>{const m=prepareManifest(manifest,'/hls/154805/20/playlist.m3u8');assert(m.body.includes('?sign=synthetic-fixture-only'));assert.equal(m.referenceCount,1);assert.deepEqual(m.referenceHosts,['cdn2.dramaflix.net']);const r=prepareManifest(manifest.replace('https://cdn2.dramaflix.net/fixture/one.ts','/fixture/one.ts'),'/hls/154805/20/playlist.m3u8');assert(r.body.includes('https://dramadunyam.com/fixture/one.ts?sign=synthetic-fixture-only'));});
test('foreign HTTP/credential/master/encryption HLS references reject with no media fetch',()=>{for(const changed of [manifest.replace('cdn2.dramaflix.net','evil.invalid'),manifest.replace('https:','http:'),manifest.replace('https://cdn2','https://user:pass@cdn2'),manifest.replace('#EXTINF','#EXT-X-KEY:METHOD=AES-128,URI="key"\n#EXTINF'),manifest.replace('#EXTINF','#EXT-X-STREAM-INF:BANDWIDTH=1\n#EXTINF')])assert.throws(()=>prepareManifest(changed,'/hls/154805/20/playlist.m3u8'));});
test('only English advertised subtitle language selected; no Arabic fallback',()=>{assert.equal(englishSubtitleLanguage(['AR','ZH']),null);assert.equal(englishSubtitleLanguage(['AR','en-US']),'en-US');assert.equal(englishSubtitleLanguage(['English']),'English');assert.throws(()=>englishSubtitleLanguage(['en/../secret']));});
test('English VTT cues are bounded and markup stripped',()=>{assert.deepEqual(parseEnglishVTT('WEBVTT\n\n1\n00:00:01.000 --> 00:00:03.000\n<b>Hello</b> &amp; welcome.\n'),[{start:1,end:3,text:'Hello & welcome.'}]);assert.throws(()=>parseEnglishVTT('WEBVTT\n\n00:00:04.000 --> 00:00:03.000\nbad'));});
test('real-path metadata client issues fresh guest cookie only sameorigin; receipts redacted',async()=>{const f=fake(normal),c=createSourceClient(f);const p=await c.fetchPlatformDirectory(new AbortController().signal);assert.equal(p.platforms.length,43);assert.equal(p.receipt.requests.length,2);assert.equal(p.cached,false);assert.equal(f.seen[0].options.headers.Cookie,undefined);assert.equal(f.seen[1].options.headers.Cookie,'dd_bilet=synthetic-guest-fixture');assert(!JSON.stringify(p.receipt).includes('synthetic-guest-fixture'));assert(!JSON.stringify(p.receipt).includes('lang='));});
test('memory cache is bounded no fresh claims on cache hits; clear refreshes',async()=>{const f=fake(normal),c=createSourceClient(f),s=new AbortController().signal;await c.fetchPlatformDirectory(s);const cached=await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,2);assert.equal(cached.cached,true);assert.equal(cached.receipt.cached,true);c.clearCache();await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,4);});
test('clear cache epoch prevents older in-flight metadata repopulating new generation',async()=>{let release;const gate=new Promise(r=>release=r);const f=fake(async u=>{if(u.pathname==='/api/platforms'&&!release.done){await gate;release.done=true;}return normal(u);}),c=createSourceClient(f),s=new AbortController().signal;const pending=c.fetchPlatformDirectory(s);while(f.seen.length<2)await new Promise(r=>setTimeout(r,1));c.clearCache();release();await pending;await c.fetchPlatformDirectory(s);assert.equal(f.seen.length,4);});
test('general resolver supports issued detail E1/E55, not fixed4 late samples',async()=>{const generic={...detail,id:'987654',slug:'new-real-catalogue-title',platform:'SerialPlus',title:'Original audio title'};const f=fake(u=>u.pathname==='/api/series/'+generic.slug?response(generic):normal(u)),c=createSourceClient(f),s=new AbortController().signal;const d=await c.fetchDetail(generic.slug,s);const r=await c.resolveEpisode(d,55,s);assert.equal(r.identity.seriesId,'987654');assert.equal(r.episodeNumber,55);assert.equal(r.subtitleStatus,'no-english-sidecar');assert.equal(r.transport,'app-cache-manifest-direct-https-segments');assert.equal(r.cdnCredentialsAttached,false);assert.equal(f.seen.filter(x=>x.u.hostname!=='dramadunyam.com').length,0);assert(f.seen.some(x=>x.u.pathname==='/hls/987654/55/playlist.m3u8'));});
test('forged detail and nonadvertised ordinal reject before any request',async()=>{const f=fake(normal),c=createSourceClient(f),s=new AbortController().signal;await assert.rejects(c.resolveEpisode(parseDetail(detail),20,s),e=>e.code==='DETAIL_NOT_ISSUED');assert.equal(f.seen.length,0);const d=await c.fetchDetail(detail.slug,s),before=f.seen.length;await assert.rejects(c.resolveEpisode(d,56,s),e=>e.code==='EPISODE_NOT_ADVERTISED');assert.equal(f.seen.length,before);});
test('English sidecar fetch is ordinary sameorigin only; no other-language file',async()=>{const f=fake(u=>u.pathname.startsWith('/api/subtitles/')?response(['AR','EN']):u.pathname.startsWith('/sub/')?response('WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nEnglish fixture.'):normal(u)),c=createSourceClient(f),s=new AbortController().signal;const d=await c.fetchDetail(detail.slug,s),r=await c.resolveEpisode(d,20,s);assert.equal(r.subtitleStatus,'english-sidecar');assert.equal(r.englishSubtitleCues.length,1);assert(f.seen.some(x=>x.u.pathname==='/sub/154805/20/EN'));assert(!f.seen.some(x=>x.u.pathname.endsWith('/AR')));});
test('gated HTTP403 remains explicit error, never auto-unlocks/retryloops',async()=>{const f=fake(u=>u.pathname.startsWith('/hls/')?response('guest gate',403):normal(u)),c=createSourceClient(f),s=new AbortController().signal,d=await c.fetchDetail(detail.slug,s);await assert.rejects(c.resolveEpisode(d,20,s),e=>e instanceof SourceError&&e.code==='HTTP_403'&&e.receipt.requests.at(-1).status===403);assert.equal(f.seen.filter(x=>x.u.pathname.startsWith('/hls/')).length,1);});
test('wrong contenttype/json, missing guestcookie and body bound remain typed errors',async()=>{for(const [value,headers,code] of [[{lang:'en'},{},'FRESH_GUEST_SESSION_MISSING'],['notjson',{'content-type':'application/json','set-cookie':'dd_bilet=fixture; Secure'},'INVALID_JSON'],['x'.repeat(131073),{'content-type':'application/json','set-cookie':'dd_bilet=fixture; Secure'},'BODY_LIMIT']]){const f=fake(()=>response(value,200,headers)),c=createSourceClient(f);await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code===code);}});
test('abort before and during stalled fetch produces ABORTED, no stale cache result',async()=>{const a=new AbortController();a.abort();const f=fake(normal),c=createSourceClient(f);await assert.rejects(c.fetchHome(a.signal),e=>e.code==='ABORTED');assert.equal(f.seen.length,0);const b=new AbortController(),c2=createSourceClient({fetchImpl:()=>new Promise(()=>{})});const p=c2.fetchPlatforms(b.signal);setTimeout(()=>b.abort(),10);await assert.rejects(p,e=>e.code==='ABORTED');});
test('whole-operation deadline includes queue and blocked body read',async()=>{const c=createSourceClient({fetchImpl:()=>new Promise(()=>{}),deadlineMs:20});await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code==='DEADLINE_EXCEEDED');});
test('global operation concurrency stays≤2 with normal guest requests',async()=>{let active=0,max=0;const f=fake(async u=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,3));active--;return normal(u);}),c=createSourceClient(f),s=new AbortController().signal;await Promise.all([c.fetchPlatforms(s),c.fetchHome(s),c.searchCatalogue('eternal',{},s),c.fetchCatalogue({},s)]);assert(max<=2);});
test('malicious redirect is rejected, never fetches foreign target',async()=>{const f=fake(()=>{const r=response({lang:'en'});Object.defineProperty(r,'url',{value:'https://foreign.invalid/api/config'});return r;}),c=createSourceClient(f);await assert.rejects(c.fetchPlatforms(new AbortController().signal),e=>e.code==='REDIRECT_REJECTED');assert.equal(f.seen.length,1);});
