import React,{useEffect,useState,useRef} from 'react';
import {AppState,ScrollView,View,StyleSheet,Pressable,Alert} from 'react-native';
import {ScaledText as Text,FontScaleContext} from './ScaledText';
import {SubtitleOverlay} from './SubtitleOverlay';
import type {PlaybackPreferences} from '../library-policy';
import {native,type InstalledVersion} from '../native';
import {checkForUpdate,getLastUpdateCheck,downloadUpdate,cancelUpdate,getUpdateStatus,installVerifiedUpdate,releaseVersionStatus,type UpdateCheck,type UpdateStatus} from '../updates';
import {ActionButton} from './Primitives';
import {colors,type,layout,radius,type MainTab,type ScreenInsets} from '../theme';
import {BrandedHeader,BottomTabs} from './Navigation';
export function SettingsScreen({preferences,onChange,insets,onTabChange,onExportLibrary,onImportLibrary}:{onExportLibrary?:()=>Promise<boolean>;onImportLibrary?:()=>Promise<boolean>;preferences:PlaybackPreferences;onChange:(value:PlaybackPreferences)=>void;insets:ScreenInsets;onTabChange:(value:MainTab)=>void}){
 const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [transferring,setTransferring]=useState(false),[transferResult,setTransferResult]=useState<string|null>(null),transferBusy=useRef(false);
 const transfer=async(kind:'export'|'import')=>{if(transferBusy.current)return;transferBusy.current=true;setTransferring(true);setTransferResult(null);try{const done=await (kind==='export'?onExportLibrary?.():onImportLibrary?.());if(alive.current)setTransferResult(done?(kind==='export'?'Library export verified. Keep this file before reinstalling.':'Library imported. Saved titles and resume points are restored.'):'Transfer cancelled. Your library is unchanged.');}catch(e){if(alive.current)setTransferResult(e instanceof Error?e.message:'Transfer failed. Your current library is unchanged.');}finally{transferBusy.current=false;if(alive.current)setTransferring(false);}};
 const [version,setVersion]=useState<InstalledVersion|null>(null),[error,setError]=useState(false);
 const versionGeneration=useRef(0);
 const load=()=>{const generation=++versionGeneration.current;setError(false);void native.reelmGetInstalledVersion().then(value=>{if(alive.current&&generation===versionGeneration.current){setVersion(value);setUpdateCheck(previous=>{if(previous?.status!=='available')return previous;const status=releaseVersionStatus(previous.releaseTag??'',value.versionName);return status==='available'?previous:{...previous,status,candidate:null};});}}).catch(()=>{if(alive.current&&generation===versionGeneration.current)setError(true);});};
 const [updateCheck,setUpdateCheck]=useState<UpdateCheck|null>(getLastUpdateCheck()),[updateStatus,setUpdateStatus]=useState<UpdateStatus|null>(null),[updateError,setUpdateError]=useState<string|null>(null),[checking,setChecking]=useState(false),[updateAction,setUpdateAction]=useState<string|null>(null);
 const checkController=useRef<AbortController|null>(null),updateGeneration=useRef(0),updateActionRef=useRef<string|null>(null),updateActionEpoch=useRef(0),updateForeground=useRef(AppState.currentState==='active');
 const refreshUpdate=async()=>{const generation=++updateGeneration.current;try{const value=await getUpdateStatus();if(alive.current&&generation===updateGeneration.current){setUpdateStatus(value);setUpdateError(previous=>previous==='Update status could not be read. Retry on this device.'?null:previous);}}catch{if(alive.current&&generation===updateGeneration.current){setUpdateStatus(null);setUpdateError('Update status could not be read. Retry on this device.');}}};
 const check=async()=>{
  if(checkController.current||updateActionRef.current)return;
  const controller=new AbortController();checkController.current=controller;setChecking(true);setUpdateError(null);
  try{const result=await checkForUpdate(controller.signal);if(alive.current&&!controller.signal.aborted){setUpdateCheck(result);if(result.status==='current'){try{const status=await getUpdateStatus();if(alive.current&&!controller.signal.aborted&&status.state==='failed'&&status.errorCode==='UPDATE_DOWNGRADE'){await cancelUpdate();await refreshUpdate();}}catch{if(alive.current&&!controller.signal.aborted)setUpdateError('Previous update status could not be refreshed. Retry on this device.');}}}}
  catch{if(alive.current&&!controller.signal.aborted){setUpdateCheck(null);setUpdateError('Update check failed. Check your connection or GitHub availability, then retry.');}}
  finally{if(checkController.current===controller)checkController.current=null;if(alive.current)setChecking(false);}
 };
 const updateWork=async(name:string,work:()=>Promise<void>)=>{
  if(updateActionRef.current&&name!=='cancel')return;
  const epoch=++updateActionEpoch.current;++updateGeneration.current;updateActionRef.current=name;setUpdateAction(name);setUpdateError(null);
  try{await work();}catch{if(alive.current&&epoch===updateActionEpoch.current)setUpdateError('Update action failed. Refresh the status and retry on this device.');}
  finally{if(alive.current&&epoch===updateActionEpoch.current)await refreshUpdate();if(epoch===updateActionEpoch.current){updateActionRef.current=null;if(alive.current)setUpdateAction(null);}}
 };
 useEffect(()=>{load();void refreshUpdate();const timer=setInterval(()=>{if(updateForeground.current)void refreshUpdate();},1000);const subscription=AppState.addEventListener('change',state=>{updateForeground.current=state==='active';if(state==='active'){load();void refreshUpdate();}});return()=>{checkController.current?.abort();++versionGeneration.current;++updateGeneration.current;clearInterval(timer);subscription.remove();};},[]);
 const updating=updateStatus?.state==='downloading'||updateStatus?.state==='installing',trusted=version?.updateTrusted===true;
 const offer=updateCheck?.status==='available'&&updateCheck.candidate;
 const progress=updateStatus?.total&&updateStatus.total>0?Math.min(100,Math.round(updateStatus.bytes/updateStatus.total*100)):undefined;
 return <View style={styles.root}><BrandedHeader title="Settings" topInset={insets.top}/><ScrollView testID="settings-scroll" contentContainerStyle={styles.content}>
  <View style={styles.section}><Text style={styles.title}>Playback</Text><Text style={styles.label}>Press-and-hold speed</Text><View style={styles.choices}>{([1.25,1.5,1.75,2] as const).map(value=><Pressable key={value} testID={`settings-speed-${value}`} accessibilityRole="button" accessibilityLabel={`Hold speed ${value} times`} accessibilityState={{selected:preferences.holdSpeed===value}} onPress={()=>onChange({...preferences,holdSpeed:value})} style={[styles.choice,preferences.holdSpeed===value&&styles.selected]}><Text style={styles.label}>{value}×</Text></Pressable>)}</View></View>
  <View style={styles.section}><Text style={styles.title}>Subtitle size</Text><View style={styles.choices}>{([.9,1,1.15,1.3] as const).map(value=><Pressable key={value} testID={`settings-font-${value}`} accessibilityRole="button" accessibilityLabel={`Subtitle size ${Math.round(value*100)} percent`} accessibilityState={{selected:preferences.fontScale===value}} onPress={()=>onChange({...preferences,fontScale:value})} style={[styles.choice,preferences.fontScale===value&&styles.selected]}><Text style={styles.label}>{Math.round(value*100)}%</Text></Pressable>)}</View><Text style={styles.copy}>Changes app-rendered subtitles only. Built-in video captions stay unchanged. Your system text size still applies.</Text><View testID="settings-subtitle-preview" style={styles.subtitlePreview}><FontScaleContext.Provider value={preferences.fontScale}><SubtitleOverlay text="Your subtitle preview" bottomInset={0} chromeVisible={false}/></FontScaleContext.Provider></View></View>
  <View style={styles.section}><Text style={styles.title}>App updates</Text><Text testID="updates-version" style={styles.copy}>{version?`Version ${version.versionName} (${version.versionCode})`:error?'Version could not be read.':'Reading installed version…'}</Text>{error?<ActionButton label="Retry installed version" tone="quiet" onPress={load}/>:null}
   {version&&!trusted?<Text style={styles.copy}>This installation needs the one-time private-signing migration before in-app updates.</Text>:null}
   <Text testID="updates-result" accessibilityLiveRegion="polite" style={styles.copy}>{checking?'Checking GitHub…':updateCheck?updateCheck.status==='available'?`Release ${updateCheck.releaseTag} is available. Download to verify compatibility.`:updateCheck.status==='unverified'?'The latest release is unverified. A unique compatible APK and published SHA256 are required.':updateCheck.releaseTag?'No newer public release is available.':'No public update release is available.':'Check GitHub manually for a new release.'}</Text>
   {updateCheck?<Text testID="updates-last-check" style={styles.copy}>Last checked {new Date(updateCheck.checkedAt).toLocaleString()}</Text>:null}
   {updateStatus?.state==='downloading'?<Text testID="updates-progress" accessibilityRole="progressbar" accessibilityLiveRegion="polite" accessibilityValue={progress===undefined?{text:`${formatBytes(updateStatus.bytes)} received`}:{min:0,max:100,now:progress}} style={styles.copy}>{formatBytes(updateStatus.bytes)} received{updateStatus.total===null?' · total unknown':` / ${formatBytes(updateStatus.total)} · ${progress}%`}</Text>:null}
   {updateStatus?.state==='verified'?<Text accessibilityLiveRegion="polite" style={styles.copy}>APK verified on this device. Android will ask you to confirm installation.</Text>:null}
   {updateStatus?.errorCode&&updateStatus.state!=='failed'?<Text accessibilityLiveRegion="polite" style={styles.error}>{updateStatus.errorCode==='UPDATE_PERMISSION_REQUIRED'?'Allow installs for Reelm Drama in Android settings, then tap Install again.':updateStatus.errorCode.endsWith('CANCELLED')?'Installation was cancelled. Tap Install to try again.':`Android did not install the APK (${updateStatus.errorCode}). Tap Install to retry.`}</Text>:null}
   {updateStatus?.state==='installing'?<Text accessibilityLiveRegion="polite" style={styles.copy}>Continue in Android to allow or confirm installation. The installed version will be checked when you return.</Text>:null}
   {updateStatus?.state==='failed'?<Text accessibilityLiveRegion="polite" style={styles.error}>Update failed ({updateStatus.errorCode??'UPDATE_FAILED'}). Check again or retry.</Text>:null}
   {updateError?<Text accessibilityLiveRegion="polite" style={styles.error}>{updateError}</Text>:null}
   <View style={styles.choices}>
    <ActionButton label={checking?'Checking…':'Check'} accessibilityLabel="Check GitHub for app updates" tone="secondary" disabled={checking||!!updateAction||updating} onPress={()=>void check()} testID="updates-check"/>
    {trusted&&offer&&!updating&&updateStatus?.state!=='verified'?<ActionButton label={updateStatus?.state==='failed'?'Retry':'Download'} accessibilityLabel={updateStatus?.state==='failed'?'Retry APK download':'Download and verify app update'} disabled={checking||!!updateAction||updateStatus===null} onPress={()=>void updateWork('download',()=>downloadUpdate(offer))} testID={updateStatus?.state==='failed'?'updates-retry':'updates-download'}/>:null}
    {updateStatus?.state==='downloading'||updateAction==='download'?<ActionButton label="Cancel" accessibilityLabel="Cancel APK download" tone="quiet" disabled={updateAction==='cancel'} onPress={()=>void updateWork('cancel',cancelUpdate)} testID="updates-cancel"/>:null}
    {trusted&&updateStatus?.state==='verified'?<ActionButton label="Install" accessibilityLabel="Install verified APK with Android confirmation" disabled={checking||!!updateAction} onPress={()=>void updateWork('install',installVerifiedUpdate)} testID="updates-install"/>:null}
    {updateStatus===null&&!updating?<ActionButton label="Refresh" accessibilityLabel="Refresh app update status" tone="quiet" onPress={()=>void refreshUpdate()} testID="updates-refresh"/>:null}
   </View>
  </View>
 {onExportLibrary&&onImportLibrary?<View style={styles.section}><Text style={styles.title}>Library transfer</Text><Text style={styles.copy}>Export Saved, Recents, resume points and preferences, or restore them from a library file.</Text><View style={styles.choices}><ActionButton label="Export" accessibilityLabel="Export library and preferences" testID="library-export" tone="primary" disabled={transferring} onPress={()=>void transfer('export')}/><ActionButton label="Import" accessibilityLabel="Import library and preferences" testID="library-import" tone="secondary" disabled={transferring} onPress={()=>Alert.alert('Replace library?', 'Import replaces Saved, Recents, progress and preferences. Export first if you want to keep the current library.',[{text:'Cancel',style:'cancel'},{text:'Import',onPress:()=>void transfer('import')}])}/></View>{transferResult?<Text accessibilityLiveRegion="polite" style={styles.copy}>{transferResult}</Text>:null}</View>:null}
 </ScrollView><BottomTabs active="settings" onChange={onTabChange} bottomInset={insets.bottom}/>
 </View>;
}
const formatBytes=(value:number)=>value<1048576?`${Math.ceil(value/1024)} KiB`:`${(value/1048576).toFixed(1)} MiB`;
const styles=StyleSheet.create({
 root:{flex:1,backgroundColor:colors.background},content:{padding:layout.gutter,gap:28,paddingBottom:32},section:{gap:12},title:{...type.title,color:colors.text},label:{...type.label,color:colors.text},copy:{...type.body,color:colors.secondary},error:{...type.body,color:colors.error},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{minWidth:64,minHeight:48,padding:12,justifyContent:'center',borderWidth:1,borderColor:colors.line},selected:{borderColor:colors.signal,backgroundColor:colors.surfaceHigh},
 subtitlePreview:{height:180,backgroundColor:colors.deep,borderWidth:1,borderColor:colors.line,borderRadius:radius.media,overflow:'hidden'},
});
