import test from 'node:test';
import assert from 'node:assert/strict';
import {componentHarness,byID,nodes} from '../tests/ui-harness.mjs';
import * as theme from '../theme.ts';
import {safeInset} from './format.ts';
const tick=()=>new Promise(setImmediate),idle={state:'idle',bytes:0,total:null,errorCode:null};
const candidate={releaseTag:'v0.2.1',assetName:'ReelmDrama-arm64-v8a.apk',url:'https://github.com/azeez-d3v/reelmdrama/releases/download/v0.2.1/ReelmDrama-arm64-v8a.apk',bytes:1000,sha256:'a'.repeat(64)};
function setup(){
 const events=[],alerts=[],state={status:idle,version:{versionName:'0.2.0',versionCode:3,updateTrusted:true},result:{status:'available',candidate,releaseTag:'v0.2.1',checkedAt:1234567890000},last:null},listeners=new Set(),timers=new Set();
 const api={getLastUpdateCheck:()=>state.last,checkForUpdate:async signal=>{events.push('check');assert(!signal.aborted);state.last=state.result;return state.result;},getUpdateStatus:async()=>state.status,downloadUpdate:async value=>{events.push(['download',value]);state.status={state:'downloading',bytes:250,total:1000,errorCode:null};},cancelUpdate:async()=>{events.push('cancel');state.status=idle;},installVerifiedUpdate:async()=>{events.push('install');state.status={state:'installing',bytes:1000,total:1000,errorCode:null};}};
 const h=componentHarness('../ui/SettingsScreen.tsx',{'./ScaledText':{ScaledText:'Text'},'../theme':theme,'./Primitives':{ActionButton:'ActionButton',IconButton:'IconButton'},'./Navigation':{BrandedHeader:'Header',BottomTabs:'Tabs'},'./Motion':{useReducedMotion:()=>false},'./format':{safeInset},'./measurement':{MeasurementProvider:'Measurements',NativeMeasurementRoot:'MeasurementRoot'},'../downloads':{listDownloads:async()=>[],downloadStorageBytes:async()=>0,groupDownloads:()=>[]},'../updates':api,'../native':{native:{reelmGetInstalledVersion:async()=>{events.push('version');return state.version;}}},'react-native':{Alert:{alert:(...args)=>alerts.push(args)},FlatList:'FlatList',ScrollView:'ScrollView',Modal:'Modal',useWindowDimensions:()=>({height:800,width:360}),AppState:{currentState:'active',addEventListener:(name,fn)=>{listeners.add(fn);return {remove:()=>listeners.delete(fn)};}}}},[],{AbortController,Date,setInterval:fn=>{timers.add(fn);return fn;},clearInterval:fn=>timers.delete(fn)});
 const props={preferences:{holdSpeed:1.5,fontScale:1},insets:{top:28,bottom:24},onChange(){},onTabChange(){},onWatchDownload(){},onDeleteDownloads:async()=>{}};
 const render=()=>h.render('SettingsScreen',props),flush=async()=>{await tick();return render();},poll=async()=>{for(const fn of timers)fn();return flush();},foreground=async()=>{for(const fn of listeners)fn('active');return flush();};
 return {h,api,state,events,alerts,props,render,flush,poll,foreground,listeners,timers};
}
const text=tree=>nodes(tree).filter(n=>n.type==='Text').map(n=>n.props.children.flat().join('')).join('\n');
test('Settings checks manually, announces release/version/last check and starts one explicit download',async()=>{
 const f=setup();try{f.render();let tree=await f.flush();assert(byID(tree,'updates-check'));assert(!f.events.includes('check'));assert.match(text(tree),/Version 0.2.0 \(3\)/);await byID(tree,'updates-check').props.onPress();tree=await f.flush();assert.match(text(tree),/v0.2.1/);assert.match(text(tree),/Last checked/);assert(byID(tree,'updates-download'));assert(!byID(tree,'updates-install'));await byID(tree,'updates-download').props.onPress();tree=await f.flush();assert.deepEqual(f.events.find(Array.isArray),['download',candidate]);assert(byID(tree,'updates-cancel'));assert.equal(byID(tree,'updates-progress').props.accessibilityValue.now,25);}finally{f.h.cleanup();}
});
test('native verification alone reveals normal Android install; return refreshes actual installed version/status',async()=>{
 const f=setup();try{f.state.status={state:'verified',bytes:1000,total:1000,errorCode:null};f.render();let tree=await f.flush();assert(byID(tree,'updates-install'));assert(!byID(tree,'updates-download'));await byID(tree,'updates-install').props.onPress();tree=await f.flush();assert(f.events.includes('install'));assert.match(text(tree),/Android/);assert(!byID(tree,'updates-install'));f.state.version={...f.state.version,versionName:'0.2.1',versionCode:4};f.state.status=idle;tree=await f.foreground();assert.match(text(tree),/Version 0.2.1 \(4\)/);assert(!byID(tree,'updates-install'));}finally{f.h.cleanup();}assert.equal(f.listeners.size,0);assert.equal(f.timers.size,0);
});
test('cancel, transfer failure, retry and unknown total remain honest and reachable',async()=>{
 const f=setup();try{f.render();await f.flush();await byID(f.render(),'updates-check').props.onPress();await f.flush();await byID(f.render(),'updates-download').props.onPress();await f.flush();f.state.status={state:'downloading',bytes:200,total:null,errorCode:null};let tree=await f.poll();assert.match(text(tree),/received/);assert.equal(byID(tree,'updates-progress').props.accessibilityValue.now,undefined);await byID(tree,'updates-cancel').props.onPress();tree=await f.flush();assert(f.events.includes('cancel'));assert(!byID(tree,'updates-install'));f.state.status={state:'failed',bytes:100,total:1000,errorCode:'UPDATE_HASH_MISMATCH'};tree=await f.poll();assert.match(text(tree),/UPDATE_HASH_MISMATCH/);assert(byID(tree,'updates-retry'));await byID(tree,'updates-retry').props.onPress();await f.flush();assert.equal(f.events.filter(Array.isArray).length,2);}finally{f.h.cleanup();}
});
test('unverified release and legacy signer explain next step without offering install or download',async()=>{
 for(const legacy of [false,true]){const f=setup();try{f.state.version.updateTrusted=!legacy;if(!legacy)f.state.result={...f.state.result,status:'unverified',candidate:null};f.render();await f.flush();await byID(f.render(),'updates-check').props.onPress();const tree=await f.flush();assert(!byID(tree,'updates-download'));assert(!byID(tree,'updates-install'));assert.match(text(tree),legacy?/signing migration/:/unverified/i);}finally{f.h.cleanup();}}
});
test('check failure and native status failure leave retry controls, not success or stale install',async()=>{
 const f=setup();try{f.api.checkForUpdate=async()=>{throw Error('UPDATE_HTTP_403');};f.render();await f.flush();await byID(f.render(),'updates-check').props.onPress();let tree=await f.flush();assert.match(text(tree),/check failed/i);assert(byID(tree,'updates-check'));f.state.status={state:'verified',bytes:1000,total:1000,errorCode:null};tree=await f.poll();assert(byID(tree,'updates-install'));f.api.getUpdateStatus=async()=>{throw Error('native read failure');};tree=await f.poll();assert.match(text(tree),/status could not be read/i);assert(!byID(tree,'updates-install'));}finally{f.h.cleanup();}
});
test('install permission and cancellation remain verified with explicit recovery, not an installation success',async()=>{
 for(const code of ['UPDATE_PERMISSION_REQUIRED','INSTALL_CANCELLED']){const f=setup();try{f.state.status={state:'verified',bytes:1000,total:1000,errorCode:code};f.render();const tree=await f.flush();assert(byID(tree,'updates-install'));assert.match(text(tree),code==='UPDATE_PERMISSION_REQUIRED'?/allow installs/i:/cancelled/i);assert.doesNotMatch(text(tree),/installed successfully/i);}finally{f.h.cleanup();}}
});
test('returning after same-label native upgrade clears stale candidate without another network check',async()=>{
 const f=setup();try{f.render();await f.flush();await byID(f.render(),'updates-check').props.onPress();await f.flush();assert(byID(f.render(),'updates-download'));f.state.version={...f.state.version,versionName:'0.2.1',versionCode:4};const tree=await f.foreground();assert(!byID(tree,'updates-download'));assert.match(text(tree),/matches the latest/);assert.equal(f.events.filter(v=>v==='check').length,1);}finally{f.h.cleanup();}
});
test('pending native transfer keeps cancel usable and a cancelled original promise never restores install',async()=>{
 const f=setup();let finish;const transfer=new Promise(resolve=>finish=resolve);
 try{f.api.downloadUpdate=async()=>{f.state.status={state:'downloading',bytes:100,total:1000,errorCode:null};await transfer;};f.api.cancelUpdate=async()=>{f.state.status=idle;finish();};f.render();await f.flush();byID(f.render(),'updates-check').props.onPress();await f.flush();byID(f.render(),'updates-download').props.onPress();let tree=await f.flush();assert.equal(byID(tree,'updates-cancel').props.disabled,false);assert.equal(byID(tree,'updates-check').props.disabled,true);byID(tree,'updates-cancel').props.onPress();tree=await f.flush();assert(!byID(tree,'updates-install'));assert(!byID(tree,'updates-cancel'));assert.equal(byID(tree,'updates-check').props.disabled,false);}finally{finish();f.h.cleanup();}
});
test('late rejected download cannot clear a replacement download lock or show its obsolete action error',async()=>{
 const f=setup();let rejectA,finishB;const first=new Promise((resolve,reject)=>rejectA=reject),second=new Promise(resolve=>finishB=resolve);let starts=0;
 try{
  f.api.downloadUpdate=()=>{f.state.status={state:'downloading',bytes:100,total:1000,errorCode:null};return ++starts===1?first:second;};
  f.api.cancelUpdate=async()=>{f.state.status=idle;};f.render();await f.flush();byID(f.render(),'updates-check').props.onPress();await f.flush();
  byID(f.render(),'updates-download').props.onPress();let tree=await f.flush();byID(tree,'updates-cancel').props.onPress();tree=await f.flush();
  byID(tree,'updates-download').props.onPress();await f.flush();assert.equal(starts,2);
  f.state.status={state:'verified',bytes:1000,total:1000,errorCode:null};tree=await f.poll();assert.equal(byID(tree,'updates-install').props.disabled,true);
  rejectA(Error('cancelled old download'));tree=await f.flush();assert.doesNotMatch(text(tree),/Update action failed/);assert.equal(byID(tree,'updates-install').props.disabled,true,'replacement owns its lock even when native verification precedes bridge completion');
  finishB();tree=await f.flush();assert.equal(byID(tree,'updates-install').props.disabled,false);
 }finally{rejectA(Error('cleanup'));finishB();f.h.cleanup();}
});
test('optional library transfer dispatches only confirmed import and reports picker cancellation without success',async()=>{
 const f=setup(),calls=[];let finish;const pending=new Promise(resolve=>finish=resolve);
 try{f.render();await f.flush();assert(!byID(f.render(),'library-export'));f.props.onExportLibrary=async()=>{calls.push('export');return pending;};f.props.onImportLibrary=async()=>{calls.push('import');return true;};f.props.preferences.fontScale=1.3;let tree=f.render();const exp=byID(tree,'library-export'),imp=byID(tree,'library-import');assert.equal(exp.type,'ActionButton');assert.equal(exp.props.accessibilityLabel,'Export library and preferences');assert.equal(imp.props.accessibilityLabel,'Import library and preferences');assert(nodes(tree).some(n=>n.type==='ScrollView'));assert(nodes(tree).some(n=>n.props.style?.flexWrap==='wrap'&&n.props.children.includes(exp)));exp.props.onPress();tree=await f.flush();assert(byID(tree,'library-export').props.disabled);assert(byID(tree,'library-import').props.disabled);finish(false);tree=await f.flush();assert.match(text(tree),/Transfer cancelled. Your library is unchanged./);assert.doesNotMatch(text(tree),/export verified/);byID(tree,'library-import').props.onPress();assert.deepEqual(calls,['export']);assert.equal(f.alerts.length,1);assert.equal(f.alerts[0][2].find(v=>v.style==='cancel').onPress,undefined);f.alerts[0][2].find(v=>v.text==='Import').onPress();tree=await f.flush();assert.deepEqual(calls,['export','import']);assert.match(text(tree),/Library imported/);}finally{finish(false);f.h.cleanup();}
});
